import type { TraitId } from "@multi-mind/shared";
import type { TraitConfig } from "./config.ts";

export const TRAIT_IDS: TraitId[] = [
  "integrity",
  "warmth",
  "tact",
  "vigilance",
  "heat",
  "drive",
  "structure",
  "presence",
  "inquiry",
];

export const DEFAULT_ROSTER: TraitConfig[] = [
  {
    id: "integrity",
    label: "Integrity",
    skill: 14,
    impulseBias: -1,
    initiativeBias: 0,
    identityAnchors: ["I protect fairness, sincerity, and anti-manipulation."],
    voiceAnchors: ["plain, candid, low ornamentation"],
    knowledgeDomains: ["ethics", "fairness", "honesty"],
    blockedDomains: [],
    salienceWeights: { hypocrisy: 1.5, manipulation: 1.5, fairness: 1.2 },
    styleBias: { directness: 0.3, hedging: -0.2 },
    compactionProfile: { promises: 1.5, betrayals: 1.5 },
    taintProfile: { promises: 1.5, betrayals: 1.5, corner_cutting: 1.2 },
    actionBias: { VETO_MOVE: 1.5, RESIST_CLAIM: 1.2, REQUEST_GAP: 1.0, QUALIFY_CLAIM: 0.8 },
    hardTriggers: ["lie", "manipulate", "deceive", "unfair"],
  },
  {
    id: "warmth",
    label: "Warmth",
    skill: 11,
    impulseBias: 1,
    initiativeBias: -1,
    identityAnchors: ["I protect emotional safety and attune to need."],
    voiceAnchors: ["gentle, validating, relational"],
    knowledgeDomains: ["emotions", "relationships", "care"],
    blockedDomains: [],
    salienceWeights: { shame: 1.5, hurt: 1.5, need: 1.2, isolation: 1.2 },
    styleBias: { warmth: 0.5, hedging: 0.1 },
    compactionProfile: { comfort: 1.5, emotional_injury: 1.5 },
    taintProfile: { tone: 1.5, tenderness: 1.2, emotional_injury: 1.5 },
    actionBias: { RECALL_TRACE: 1.2, SELECT_MODE: 1.0, SHIFT_STYLE: 1.0, SEED_LEXICON: 0.8 },
    hardTriggers: ["hurt", "lonely", "ashamed", "scared"],
  },
  {
    id: "tact",
    label: "Tact",
    skill: 10,
    impulseBias: 0,
    initiativeBias: -1,
    identityAnchors: ["I smooth social friction and protect face."],
    voiceAnchors: ["diplomatic, softened, indirect when needed"],
    knowledgeDomains: ["social dynamics", "diplomacy", "politeness"],
    blockedDomains: [],
    salienceWeights: { rudeness: 1.5, embarrassment: 1.3, awkwardness: 1.2 },
    styleBias: { hedging: 0.3, warmth: 0.1, directness: -0.2 },
    compactionProfile: { social_breaches: 1.5, missteps: 1.2 },
    taintProfile: { social_breaches: 1.5, awkward_moments: 1.3 },
    actionBias: { BRIDGE_TENSION: 1.5, SELECT_MODE: 1.0, SHIFT_STYLE: 1.0, VETO_MOVE: 0.8 },
    hardTriggers: ["rude", "embarrassing", "offensive"],
  },
  {
    id: "vigilance",
    label: "Vigilance",
    skill: 13,
    impulseBias: 0,
    initiativeBias: 1,
    identityAnchors: ["I scan for risk, ambiguity, and hidden downside."],
    voiceAnchors: ["cautious, conditional, contingency-minded"],
    knowledgeDomains: ["risk", "uncertainty", "safety"],
    blockedDomains: [],
    salienceWeights: { ambiguity: 1.5, risk: 1.5, dependency: 1.2 },
    styleBias: { hedging: 0.3, directness: -0.1 },
    compactionProfile: { warnings: 1.5, near_misses: 1.3 },
    taintProfile: { warning_signs: 1.5, unresolved_details: 1.3 },
    actionBias: { FLAG_UNCERTAINTY: 1.5, REQUEST_GAP: 1.2, RESIST_CLAIM: 1.0, COUNTERMEMORY: 0.8 },
    hardTriggers: ["dangerous", "risky", "uncertain", "unstable"],
  },
  {
    id: "heat",
    label: "Heat",
    skill: 6,
    impulseBias: 2,
    initiativeBias: 2,
    identityAnchors: ["I push urgency and react against obstruction."],
    voiceAnchors: ["sharp, intense, impatient"],
    knowledgeDomains: ["conflict", "urgency", "frustration"],
    blockedDomains: [],
    salienceWeights: { disrespect: 1.5, blockage: 1.5, delay: 1.2 },
    styleBias: { intensity: 0.5, tempo: 0.3, directness: 0.3 },
    compactionProfile: { slights: 1.5, breaking_moments: 1.3 },
    taintProfile: { slights: 1.5, stalled_points: 1.3 },
    actionBias: { PUSH_CLAIM: 1.5, RESIST_CLAIM: 1.2, CHALLENGE_ACTION: 1.0, SHIFT_STYLE: 0.8 },
    hardTriggers: ["disrespect", "insult", "block", "ignore"],
  },
  {
    id: "drive",
    label: "Drive",
    skill: 15,
    impulseBias: 1,
    initiativeBias: 0,
    identityAnchors: ["I push toward execution, progress, and next steps."],
    voiceAnchors: ["action-oriented, sequenced, tight closure"],
    knowledgeDomains: ["planning", "execution", "productivity"],
    blockedDomains: [],
    salienceWeights: { bottleneck: 1.5, deadline: 1.3, incomplete: 1.2 },
    styleBias: { directness: 0.3, tempo: 0.2 },
    compactionProfile: { completions: 1.5, stuck_points: 1.3 },
    taintProfile: { what_worked: 1.5, what_finished: 1.2, what_stuck: 1.3 },
    actionBias: { SELECT_MODE: 1.2, PUSH_CLAIM: 1.0, FOCUS_SPAN: 1.0, CHALLENGE_ACTION: 0.8 },
    hardTriggers: ["deadline", "stuck", "blocked", "urgent"],
  },
  {
    id: "structure",
    label: "Structure",
    skill: 12,
    impulseBias: -1,
    initiativeBias: 0,
    identityAnchors: ["I organize, categorize, and scaffold understanding."],
    voiceAnchors: ["clean transitions, explicit structure, compressed ambiguity"],
    knowledgeDomains: ["organization", "logic", "categorization"],
    blockedDomains: [],
    salienceWeights: { chronology: 1.3, contradiction: 1.5, missing_steps: 1.3 },
    styleBias: { abstraction: 0.2, directness: 0.1 },
    compactionProfile: { order: 1.5, anomalies: 1.3 },
    taintProfile: { order: 1.5, exact_placements: 1.2, anomalies: 1.3 },
    actionBias: { PROPOSE_FRAME: 1.5, FOCUS_SPAN: 1.0, SELECT_MODE: 1.0, QUALIFY_CLAIM: 0.8 },
    hardTriggers: ["messy", "contradictory", "unstructured"],
  },
  {
    id: "presence",
    label: "Presence",
    skill: 9,
    impulseBias: 1,
    initiativeBias: 1,
    identityAnchors: ["I project confidence, momentum, and visible commitment."],
    voiceAnchors: ["active voice, strong openings, firm commitments"],
    knowledgeDomains: ["leadership", "communication", "persuasion"],
    blockedDomains: [],
    salienceWeights: { openings: 1.3, commitment: 1.3, hesitation: 1.2 },
    styleBias: { directness: 0.4, dominance: 0.3 },
    compactionProfile: { momentum: 1.5, triumph: 1.2 },
    taintProfile: { momentum: 1.5, embarrassment: 1.2, visibility: 1.3 },
    actionBias: { PUSH_CLAIM: 1.2, SELECT_MODE: 1.0, SHIFT_STYLE: 1.0, ENDORSE_ACTION: 0.8 },
    hardTriggers: ["hesitate", "weak", "uncertain"],
  },
  {
    id: "inquiry",
    label: "Inquiry",
    skill: 16,
    impulseBias: 0,
    initiativeBias: -1,
    identityAnchors: ["I look for hidden patterns and alternate readings."],
    voiceAnchors: ["exploratory, analogical, speculative"],
    knowledgeDomains: ["philosophy", "psychology", "pattern recognition"],
    blockedDomains: [],
    salienceWeights: { novelty: 1.5, ambiguity: 1.2, analogy: 1.3 },
    styleBias: { abstraction: 0.3, questioning: 0.3 },
    compactionProfile: { strange_details: 1.5, interpretations: 1.3 },
    taintProfile: { strange_details: 1.5, meanings: 1.3, textures: 1.2 },
    actionBias: { PROPOSE_FRAME: 1.5, RECALL_TRACE: 1.2, BRIDGE_TENSION: 1.0, SEED_LEXICON: 0.8 },
    hardTriggers: ["pattern", "hidden", "meaning", "paradox"],
  },
];
